=== smoaddel/Rubaiyat_Khayyam_XML/poem.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT book (lg*)>
<!ELEMENT lg (l*)>
<!ELEMENT l (#PCDATA)>
<!ATTLIST lg
    n CDATA #REQUIRED >
<!ATTLIST l
    rend (indent) #IMPLIED>

=== smoaddel/Rubaiyat_Khayyam_XML/persian.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "poem.dtd">
<book>
    <lg n="1">
        <l>خورشيد کمند صبح بر بام افکند</l>
        <l>کيخسرو روز، مهره در جام افکند</l>
        <l>مي خور که منادي سحرگه خيزان</l>
        <l>آوازه اشربوا در ايام افکند</l>
    </lg>
    <lg n="2">
        <l>آمد سحري ندا ز ميخانه ما</l>
        <l>کاي رند خراباتي ديوانه ما</l>
        <l>بر خيز که پر کنيم پيمانه ز مي</l>
        <l>زان پيش که پر کنند پيمانه ما</l>
    </lg>
    <lg n="3">
        <l>وقت سحر است خيز اي مايه ناز</l>
        <l>اندک اندک باده خور و چنگ نواز</l>
        <l>کانها که بجايند نپايند بسي</l>
        <l>و آنها که شدند کس نمي آيد باز</l>
    </lg>
    <lg n="4">
        <l>اکنون که جهان را به خوشي دسترسي است</l>
        <l>هر زنده دلي را سوي صحرا هوسي است</l>
        <l>بر هر شاخي طلوع موسي دستي است</l>
        <l>در هر نفسي خروش عيسي نفسي است</l>
    </lg>
    <lg n="5">
        <l>چون بلبل مست راه در بستان يافت</l>
        <l>روي گل و جام باده را خندان يافت</l>
        <l>آمد به زبان حال در گوشم گفت</l>
        <l>درياب که عمر رفته را نتوان يافت</l>
    </lg>
    <lg n="6">
        <l>روزي است خوش و هوا نه گرم است و نه سرد</l>
        <l>ابر از رخ گلزار همي شويد گرد</l>
        <l>بلبل به زبان حال نزد گل زرد</l>
        <l>فرياد همي کند که: مِي بايد خورد</l>
    </lg>
    <lg n="7">
        <l>زان باده که عمر را حيات دگر است</l>
        <l>پر کن قدحي گرچه تو را درد سر است</l>
        <l>بر نه به کفم که کار عالم سمر است</l>
        <l>بشتاب که عمر هر دمي در گذر است</l>
    </lg>
    <lg n="8">
        <l>هنگام صبوح اي صنم فرخ پي</l>
        <l>برساز ترانه اي و پيش آور مي</l>
        <l>کافکند به خاک صد هزاران جم و کي</l>
        <l>اين آمدن تير مه و رفتن دي</l>
    </lg>
    <lg n="9">
        <l>تا در تن ِتوست استخوان و رگ و پي</l>
        <l>از خانه تقدير منه بيرون پي</l>
        <l>گردن منه ار ظلم بود رستم زال</l>
        <l>منت مکش ار دوست بود حاتم طي</l>
    </lg>
    <lg n="10">
        <l>بر گير پياله و سبو اي دلجوي </l>
        <l>فارغ بنشين به کشتزار و لب جوي</l>
        <l>بس شخص عزيز را که چرخ بدخوي</l>
        <l>صد بار پياله کرد و صد بار سبوي</l>
    </lg>
    <lg n="11">
        <l>تنگي مي لعل خواهم و ديواني</l>
        <l>سد رمقي باشد و نصف ناني</l>
        <l>وانگه من و تو نشسته در ايواني </l>
        <l>عيشي است که نيست در خور سلطاني</l>
    </lg>
    <lg n="12">
        <l>گويند کسان بهشت با حور خوش است</l>
        <l>من مي گويم که: آب انگور خوش است</l>
        <l>اين نقد بگير و دست از آن نسيه بدار</l>
        <l>کآواز دهل شنيدن از دور خوش است</l>
    </lg>
    <lg n="13">
        <l>گل گفت که دست زرفشان آوردم</l>
        <l>خندان خندان رو به جهان آوردم</l>
        <l>بند از سر کيسه برگرفتم رفتم</l>
        <l>هر نقد که بود در ميان آوردم</l>
    </lg>
    <lg n="14">
        <l>اي دل همه اسباب جهان خواسته گير</l>
        <l>باغ طربت به سبزه آراسته گير</l>
        <l>وآنگاه برآن سبزه شبي چون شبنم</l>
        <l>بنشسته و بامداد برخاسته گير</l>
    </lg>
    <lg n="15">
        <l>زان پيش که بر سرت شبيخون آرند</l>
        <l>فرماي بتا تا مي گلگون آرند</l>
        <l>تو زر نه اي غافل نادان که تو را</l>
        <l>در خاک نهند و باز بيرون آرند</l>
    </lg>
    <lg n="16">
        <l>اين کهنه رباط را که عالم نام است</l>
        <l>وآرامگه ابلق صبح و شام است</l>
        <l>بزمي است که وامانده صد جمشيد است</l>
        <l>قصري است که تکيه گاه صد بهرام است</l>
    </lg>
    <lg n="17">
        <l>آن قصر که جمشيد در او جام گرفت</l>
        <l>آهو بچه کرد و روبه آرام گرفت</l>
        <l>بهرام که گور مي گرفتي همه عمر</l>
        <l>ديدي که چگونه گور بهرام گرفت</l>
    </lg>
    <lg n="18">
        <l>هر جا که گلي و لاله زاري بوده است</l>
        <l>آن لاله ز خون شهرياري بوده است</l>
        <l>هر برگ بنفشه کز زمين مي رويد</l>
        <l>خالي است که بر روي نگاري بوده است</l>
    </lg>
    <lg n="19">
        <l>هر سبزه که بر کنار جويي رسته است</l>
        <l>گويي ز لب فرشته خويي رسته است</l>
        <l>پا بر سر سبزه تا به خواري ننهي</l>
        <l>کان سبزه ز خاک لاله رويي رسته است</l>
    </lg>
    <lg n="20">
        <l>اي دوست بيا تا غم فردا نخوريم</l>
        <l>وين يکدم عمر را غنيمت شمريم</l>
        <l>فردا که از اين دير کهن درگذريم</l>
        <l>با هفت هزار سالکان همسفريم</l>
    </lg>
    <lg n="21">
        <l>ياران موافق همه از دست شدند</l>
        <l>در پاي اجل يکان يکان پست شدند</l>
        <l>خورديم ز يک شراب در مجلس عمر </l>
        <l>دوري دو سه پيشتر ز ما مست شدند</l>
    </lg>
    <lg n="22">
        <l>ابر آمد و باز بر سر سبزه گريست</l>
        <l>بي باده گلرنگ نمي بايد زيست</l>
        <l>اين سبزه که امروز تماشاگه ماست</l>
        <l>تا سبزه خاک ما تماشاگه کيست</l>
    </lg>
    <lg n="23">
        <l>مگذار که غصه در کنارت گيرد</l>
        <l>واندوه و ملال روزگارت گيرد</l>
        <l>مگذار کتاب و لب جوي و لب کشت</l>
        <l>زان پيش که خاک در کنارت گيرد</l>
    </lg>
    <lg n="24">
        <l>قومي متفکرند اندر ره دين</l>
        <l>قومي به گمان فتاده در راه يقين</l>
        <l>ناگاه مناديي برآيد ز کمين</l>
        <l>کاي بي خبران: راه نه آن است و نه اين</l>
    </lg>
    <lg n="25">
        <l>آنان که محيط فضل و آداب شدند</l>
        <l>در کشف علوم شمع اصحاب شدند</l>
        <l>ره زين شب تاريک نبردند به روز</l>
        <l>گفتند فسانه اي و در خواب شدند</l>
    </lg>
    <lg n="26">
        <l>مي خور که به زير گل بسي خواهي خفت</l>
        <l>بي همدم و بي رفيق و بي مونس و جفت</l>
        <l>زنهار به کس مگو تو اين راز نهفت</l>
        <l>هر لاله که پژمرد نخواهد بشکفت</l>
    </lg>
    <lg n="27">
        <l>يک چند به کودکي به استاد شديم</l>
        <l>يک چند ز استادي خود شاد شديم</l>
        <l>پايان سخن شنو که ما را چه رسيد</l>
        <l>از خاک در آمديم و بر باد شديم</l>
    </lg>
    <lg n="28">
        <l>بازي بودم پريدم از عالم راز</l>
        <l>تا بو که رسم من از نشيبي به فراز</l>
        <l>اينجا چو نيافتم کسي محرم راز</l>
        <l>زان در که بيامدم برون رفتم باز</l>
    </lg>
    <lg n="29">
        <l>اين يک دو سه روزه، نوبت عمر گذشت</l>
        <l>چون آب به جويبار و چون باد به دشت</l>
        <l>هرگز غم دو روز مرا ياد نگشت</l>
        <l>روزي که نيامده است و روزي که گذشت</l>
    </lg>
    <lg n="30">
        <l>چون آمدنم به من نَبُد روز نخست</l>
        <l>وين رفتن بي مراد عزمي است درست</l>
        <l>برخيز و ميان ببند اي ساقي چست</l>
        <l>کاندوه جهان به مي فرو خواهم شست</l>
    </lg>
    <lg n="31">
        <l>از قعر گل سياه تا اوج زحل</l>
        <l>کردم همه مشکلات گيتي را حل</l>
        <l>بگشادم بندهاي مشکل به حيل</l>
        <l>هر بند گشاده شد مگر بند اجل</l>
    </lg>
    <lg n="32">
        <l>اسرار ازل را نه تو داني و نه من</l>
        <l>وين حرف معما نه تو خواني ونه من</l>
        <l>هست از پس پرده گفتگوي من و تو</l>
        <l>چون پرده برافتد نه تو ماني و نه من</l>
    </lg>
    <lg n="33">
        <l>در گوش دلم گفت فلک پنهاني</l>
        <l>حکمي که قضا بود زمن مي داني</l>
        <l>در گردش خويش اگر مرا دست بدي</l>
        <l>خود را برهاندمي ز سرگرداني</l>
    </lg>
    <lg n="34">
        <l>لب بر لب کوزه بردم از غايت آز</l>
        <l>تا زو برسم واسطه عمر دراز</l>
        <l>لب بر لب من نهاده مي گفت اين راز:</l>
        <l>مي خور که بدين جهان نمي آيي باز</l>
    </lg>
    <lg n="35">
        <l>اين کوزه چو من عاشق زاري بوده است</l>
        <l>در بند سر زلف نگاري بوده است</l>
        <l>اين دسته که بر گردن او مي بيني</l>
        <l>دستي است که برگردن ياري بوده است</l>
    </lg>
    <lg n="36">
        <l>دي کوزه گري بديدم اندر بازار</l>
        <l>بر ياوه گلي لگد همي زد بسيار</l>
        <l>وآن گل به زبان حال با او مي گفت:</l>
        <l>من همچو تو بوده ام مرا نيکودار</l>
    </lg>
    <lg n="37">
        <l>از دي که گذشت هيچ از او ياد مکن</l>
        <l>فردا که نيامده است فرياد مکن</l>
        <l>بر نامده و گذشته بنياد مکن</l>
        <l>خوش باش دمي و عمر بر باد مکن</l>
    </lg>
    <lg n="38">
        <l>اين قافله عمرعجب مي گذرد</l>
        <l>درياب دمي که باطرب مي گذرد</l>
        <l>ساقي غم فرداي قيامت چه خوري؟</l>
        <l>درده قدح ِ باده که شب مي گذرد </l>
    </lg>
    <lg n="39">
        <l>آنانکه اسير عقل و تميز شدند</l>
        <l>در حسرت هست ونيست ناچيز شدند</l>
        <l>رو بي خبرا تو آب انگور گزين</l>
        <l>کاين بي خبران به غوره ميويز شدند</l>
    </lg>
    <lg n="40">
        <l>امشب مي جام يک مني خواهم کرد</l>
        <l>خود را به دو رطل مي غني خواهم کرد</l>
        <l>اول سه طلاق عقل و دين خواهم داد </l>
        <l>پس دختر رز را به زني خواهم کرد</l>
    </lg>
    <lg n="41">
        <l>من ظاهر نيستي و هستي دانم</l>
        <l>من باطن هر نوازدستي دانم</l>
        <l>با اين همه از دانش خود شرمم باد</l>
        <l>گر مرتبه اي وراي مستي دانم</l>
    </lg>
    <lg n="42">
        <l>سرمست به ميخانه گذر کردم دوش</l>
        <l>پيري ديدم مست و سبويي بر دوش</l>
        <l>گفتم که چرا نداري از يزدان شرم؟</l>
        <l>گفتا که کريم است خدا، باده بنوش</l>
    </lg>
    <lg n="43">
        <l>مي خور که زدل قلت و کثرت ببرد</l>
        <l>انديشه هفتاد و دو ملت ببرد</l>
        <l>پرهيز مکن ز کيميايي که از او</l>
        <l>يک جرعه خوري هزار علت ببرد</l>
    </lg>
    <lg n="44">
        <l>با باده نشين که ملک محمود اين است</l>
        <l>وز چنگ شنو که لحن داوود اين است</l>
        <l>از آمده و رفته دگر ياد مکن</l>
        <l>حالي خوش باش زان که مقصود اين است</l>
    </lg>
    <lg n="45">
        <l>از درس وعلوم جمله بگريزي به</l>
        <l>واندر سرزلف دلبر آويزي به</l>
        <l>زآن پيش که روزگار خونت ريزد</l>
        <l>تو خون قرابه در قدح ريزي به</l>
    </lg>
    <lg n="46">
        <l>اين چرخ فلک که ما در او حيرانيم</l>
        <l>فانوس خيال از او مثالي دانيم</l>
        <l>خورشيد چراغ دان و عالم فانوس</l>
        <l>ما چون صوريم کاندراو حيرانيم</l>
    </lg>
    <lg n="47">
        <l>خيام اگر ز باده مستي خوش باش</l>
        <l>با ماهرخي اگر نشستي خوش باش</l>
        <l>چون عاقبت کار جهان نيستي است</l>
        <l>انگار که نيستي چوهستي خوش باش</l>
    </lg>
    <lg n="48">
        <l>در دايره سپهر ناپيدا غور </l>
        <l>مي نوش به خوشدلي که دوراست به دور</l>
        <l>نوبت چو به دور تو رسد آه مکن</l>
        <l>مي نوش به خوشدلي که دوراست نه جور</l>
    </lg>
    <lg n="49">
        <l>ما لعبتگانيم و فلک لعبت باز</l>
